apiVersion: v1
kind: Service
metadata:
  name: db1
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  type: ClusterIP
  ports:
   - port: 5432
     targetPort: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app